version: '1'
name: ipscm
services:
    server:
      image: simonrusu97/ipscmback
      build: 
        context: ./IPSCM
        dockerfile: Dockerfile
      ports:
        - "5000:5000"

    client:
      image: simonrusu97/ipscmfront
      build: 
        context: ./IPSCM.WebClient
        dockerfile: Dockerfile
      ports:
        - "4200:80"